// Package appicon carries the application mark. One icon serves the tray, the
// taskbar, and every desktop window, so it lives in a package both the tray and
// the desktop window backends can embed rather than in either of them.
//
// assets/source_tray_icon.png is the master artwork. Platform-specific sizes
// are generated by scripts/icons/build_windows_icon.py and build_mac_icon.py.
package appicon

import _ "embed"

// ICO is the multi-frame Windows icon used by the tray, the window class, and
// the executable's resource section.
//
//go:embed assets/tray_windows.ico
var ICO []byte

// PNG is the shared single-size mark used by the non-macOS trays.
//
//go:embed assets/tray.png
var PNG []byte

// MacPNG is the original logo resized to 1024px, which release-assets.yml turns into
// Contents/Resources/AppIcon.icns, and the bytes desktop_darwin.go hands to
// AppKit for the Dock and the application switcher.
//
// Its outputs are macOS-only; regenerating them does not alter Windows/web assets.
//
//go:embed assets/icon_mac.png
var MacPNG []byte

// MacTrayPNG is the same mark at the 32px the mac menu bar slot needs (16pt at 2x).
// It is resized directly from the original logo, without adding a text title.
//
//go:embed assets/tray_mac.png
var MacTrayPNG []byte
