import { readFileSync } from 'node:fs'
import { describe, expect, test } from 'vitest'

const source = readFileSync('src/ChatApp.jsx', 'utf8')

describe('session-scoped guided-message queue wiring', () => {
  test('prefetches state without delaying history and applies it after history', () => {
    const start = source.indexOf('const openSession = async')
    const end = source.indexOf('const refreshActiveSessionSnapshot', start)
    const open = source.slice(start, end)
    const prefetch = open.indexOf('const prefetchedState = chatApi(`/api/chat/state/${id}`, { signal: controller.signal })')
    const detail = open.indexOf('const d = await loadSessionDetail(id, { signal: controller.signal })')
    const history = open.indexOf('historyPages.apply(d,')
    const state = open.indexOf('await loadChatState(d.id, openToken, prefetchedState)')
    expect(prefetch).toBeGreaterThan(-1)
    expect(detail).toBeGreaterThan(prefetch)
    expect(history).toBeGreaterThan(detail)
    expect(state).toBeGreaterThan(history)
    expect(open).toContain('error => ({ error })')
  })

  test('discards stale prefetched state before surfacing its error', () => {
    const start = source.indexOf('const loadChatState = async')
    const load = source.slice(start, source.indexOf('const openSession = async', start))
    const awaited = load.indexOf('await prefetchedState')
    const guard = load.indexOf('if (openToken !== openSeqRef.current || !isActiveSession(id)) return null', awaited)
    const error = load.indexOf('if (result?.error) throw result.error')
    expect(awaited).toBeGreaterThan(-1)
    expect(guard).toBeGreaterThan(awaited)
    expect(error).toBeGreaterThan(guard)
  })

  test('clears stale queue immediately, then applies the selected session backend queue', () => {
    const openStart = source.indexOf('const openSession = async')
    const open = source.slice(openStart, source.indexOf('const refreshActiveSessionSnapshot', openStart))
    const clearQueue = open.indexOf('applyQueueSnapshot([])')
    const fetchSession = open.indexOf('const d = await loadSessionDetail(id, { signal: controller.signal })')
    const restoreQueue = open.indexOf('applyQueueSnapshot(d.queued_messages, d.id)')
    expect(openStart).toBeGreaterThan(-1)
    expect(clearQueue).toBeGreaterThan(-1)
    expect(fetchSession).toBeGreaterThan(clearQueue)
    expect(restoreQueue).toBeGreaterThan(fetchSession)
  })

  test('clears both queue state and ref when switching instances', () => {
    const switchStart = source.indexOf('const switchChatInstance =')
    const switchEnd = source.indexOf('\n  }', switchStart)
    const switchSource = source.slice(switchStart, switchEnd)
    expect(switchSource).toContain('applyQueueSnapshot([])')
    expect(switchSource).not.toContain('setQueuedMessages([])')
  })

  test('serializes atomic queue operations and applies backend responses', () => {
    expect(source).toContain("method:'PATCH'")
    expect(source).toContain('body:JSON.stringify({ op:operation, ...payload })')
    expect(source).not.toContain('body:JSON.stringify({ operation, ...payload })')
    expect(source).toContain('const d = await api(queueURL)')
    expect(source).toContain('applyQueueSnapshot(d.queued_messages, sessionId)')
    expect(source.match(/queueWriteRef\.current = request/g)?.length).toBeGreaterThanOrEqual(2)
    expect(source).not.toContain('body:JSON.stringify({ messages:snapshot })')
  })

  test('guiding projects the user turn immediately, then attaches to the backend-started run', () => {
    const guideStart = source.indexOf('const guideQueued = async')
    const optimisticUser = source.indexOf('id:`guided-${next.id}`', guideStart)
    const restoreFollow = source.indexOf('setFollowState(true)', optimisticUser)
    const optimisticProjection = source.indexOf('setMessages(xs => isActiveSession(id)', restoreFollow)
    const guideTry = source.indexOf('    try {', optimisticProjection)
    const abortPendingAssistant = source.indexOf("const pendingAssistantIndex = xs.findLastIndex(message => message.role === 'assistant' && !message.content)", guideTry)
    const guideURL = source.indexOf('const guideURL = `/api/chat/guide/${id}/${next.id}`', guideTry)
    const firstGuide = source.indexOf('let guideResult = await chatApi(guideURL', guideURL)
    const queuedCheck = source.indexOf("if (guideResult?.status === 'queued')", firstGuide)
    const cancel = source.indexOf('await chatApi(`/api/chat/cancel/${id}`', queuedCheck)
    const retryGuide = source.indexOf('guideResult = await chatApi(guideURL', cancel)
    const startedCheck = source.indexOf("if (guideResult?.status !== 'started')", retryGuide)
    const markStarted = source.indexOf('guideStarted = true', startedCheck)
    const activeCheck = source.indexOf('if (!isActiveSession(id)) return', markStarted)
    const refreshGuided = source.indexOf('await refreshQueue(id)', activeCheck)
    const reconnect = source.indexOf('await attachRunningStream(id, { waitForRun:true, clientUserID:guidedUser.id })', refreshGuided)
    const rollback = source.indexOf('if (!guideStarted && guidedUser)', reconnect)
    const releaseGuiding = source.indexOf('if (guidingQueueRef.current === next.id)', rollback)
    const resetRun = source.indexOf('activeRunRef.current = false', releaseGuiding)
    const guideEnd = source.indexOf('\n  }', resetRun)
    const guideFinally = source.slice(source.lastIndexOf('} finally {', resetRun), guideEnd)
    expect(guideStart).toBeGreaterThan(-1)
    expect(optimisticUser).toBeGreaterThan(guideStart)
    expect(restoreFollow).toBeGreaterThan(optimisticUser)
    expect(optimisticProjection).toBeGreaterThan(restoreFollow)
    expect(guideTry).toBeGreaterThan(optimisticProjection)
    expect(abortPendingAssistant).toBeGreaterThan(guideTry)
    expect(abortPendingAssistant).toBeLessThan(guideURL)
    expect(guideURL).toBeGreaterThan(guideTry)
    expect(firstGuide).toBeGreaterThan(guideURL)
    expect(queuedCheck).toBeGreaterThan(firstGuide)
    expect(cancel).toBeGreaterThan(queuedCheck)
    expect(retryGuide).toBeGreaterThan(cancel)
    expect(startedCheck).toBeGreaterThan(retryGuide)
    expect(markStarted).toBeGreaterThan(startedCheck)
    expect(activeCheck).toBeGreaterThan(markStarted)
    expect(refreshGuided).toBeGreaterThan(activeCheck)
    expect(reconnect).toBeGreaterThan(refreshGuided)
    expect(rollback).toBeGreaterThan(reconnect)
    expect(releaseGuiding).toBeGreaterThan(rollback)
    expect(resetRun).toBeGreaterThan(releaseGuiding)
    expect(resetRun).toBeLessThan(guideEnd)
    expect(guideFinally).not.toContain('setBusy(false)')
    expect(guideFinally).not.toContain("setStreamingSid('')")
  })

  test('reloads the active session only after cancel persistence completes', () => {
    const cancelStart = source.indexOf('const cancelRun = async')
    const abort = source.indexOf('streamAbortRef.current?.abort?.()', cancelStart)
    const persisted = source.indexOf('await chatApi(`/api/chat/cancel/${id}`', abort)
    const activeCheck = source.indexOf('if (isActiveSession(id)) await openSession(id, false)', persisted)
    const cancelEnd = source.indexOf('\n  }', activeCheck)
    expect(cancelStart).toBeGreaterThan(-1)
    expect(abort).toBeGreaterThan(cancelStart)
    expect(persisted).toBeGreaterThan(abort)
    expect(activeCheck).toBeGreaterThan(persisted)
    expect(activeCheck).toBeLessThan(cancelEnd)
  })

  test('releases local run admission before post-run session reloads', () => {
    const runStart = source.indexOf('const runSend = async')
    const terminalFinally = source.indexOf('if (runToken !== runSeqRef.current) return', runStart)
    const releaseRun = source.indexOf('activeRunRef.current = false', terminalFinally)
    const releaseBusy = source.indexOf('setBusy(false)', releaseRun)
    const releaseStreaming = source.indexOf("setStreamingSid('')", releaseBusy)
    const reloadSessions = source.indexOf('const refreshedSessions = await loadSessions(id)', terminalFinally)
    const reloadSession = source.indexOf('await openSession(id, false)', reloadSessions)
    expect(terminalFinally).toBeGreaterThan(runStart)
    expect(releaseRun).toBeGreaterThan(terminalFinally)
    expect(releaseBusy).toBeGreaterThan(releaseRun)
    expect(releaseStreaming).toBeGreaterThan(releaseBusy)
    expect(reloadSessions).toBeGreaterThan(releaseStreaming)
    expect(reloadSession).toBeGreaterThan(reloadSessions)
  })

  test('refreshes the backend queue only after a guided send has an active session', () => {
    const runStart = source.indexOf('const runSend = async')
    const activeCheck = source.indexOf('} else if (!isActiveSession(id)) {', runStart)
    const refreshGuided = source.indexOf('await refreshQueue(id)', activeCheck)
    expect(runStart).toBeGreaterThan(-1)
    expect(activeCheck).toBeGreaterThan(runStart)
    expect(refreshGuided).toBeGreaterThan(activeCheck)
  })

  test('does not replace an optimistic guided turn with a heartbeat snapshot', () => {
    const refreshStart = source.indexOf('const refreshList = async')
    const attach = source.indexOf('void attachRunningStream(activeID, { waitForRun:true })', refreshStart)
    const guardedSnapshot = source.indexOf('} else if (!guidingQueueRef.current && shouldRefreshChatSnapshot(before, after)) {', attach)
    const refreshSnapshot = source.indexOf('void refreshActiveSessionSnapshot(activeID)', guardedSnapshot)
    expect(refreshStart).toBeGreaterThan(-1)
    expect(attach).toBeGreaterThan(refreshStart)
    expect(guardedSnapshot).toBeGreaterThan(attach)
    expect(refreshSnapshot).toBeGreaterThan(guardedSnapshot)
  })

  test('reconciles only the observed local stream after the backend reports a terminal session', () => {
    const helperStart = source.indexOf('const refreshActiveSessionSnapshot = async (id) =>')
    const helperEnd = source.indexOf('\n  const loadWorldline = async', helperStart)
    const helper = source.slice(helperStart, helperEnd)
    expect(helper).toContain('const streamActivityToken = streamActivitySeqRef.current')
    expect(helper).toContain('const observedStream = streamAbortRef.current')
    expect(helper).toContain('streamActivitySeqRef.current !== streamActivityToken')
    expect(helper).toContain('if (summary?.running || streamAbortRef.current !== observedStream) return')
    expect(helper).toContain('observedStream?.abort?.()')
    expect(helper).not.toContain('streamAbortRef.current = null')
    expect(helper.indexOf('streamActivitySeqRef.current !== streamActivityToken')).toBeLessThan(helper.indexOf('observedStream?.abort?.()'))
    expect(helper.indexOf('observedStream?.abort?.()')).toBeLessThan(helper.indexOf('historyPages.apply('))

    const attachStart = source.indexOf('const attachRunningStream = async')
    const attachEnd = source.indexOf('\n  useEffect(() =>', attachStart)
    const runSendStart = source.indexOf('const runSend = async')
    const runSendEnd = source.indexOf('\n  autorunRunSendRef.current = runSend', runSendStart)
    expect(source.slice(attachStart, attachEnd)).toContain('++streamActivitySeqRef.current')
    expect(source.slice(runSendStart, runSendEnd)).toContain('++streamActivitySeqRef.current')
  })

  test('keeps queue send and stop as separate actions while the current session is running', () => {
    expect(source).toContain("disabled={sessionLoading || sessionLoadFailed || (!prompt.trim() && !attachments.length)}")
    expect(source).toContain("onClick={() => send()}")
    expect(source).toContain("ct('加入发送队列', 'Add to send queue')")
    expect(source).toContain("{isCurrentRunning && <button")
    expect(source).toContain('className="oa-stop"')
    expect(source).toContain("onClick={() => cancelRun(sid)}")
    expect(source).not.toContain("onClick={() => isCurrentRunning ? cancelRun(sid) : send()}")
  })

  test('uses SSE invalidation with authoritative GET and polling fallback', () => {
    const eventsURL = source.indexOf('`/api/chat/queue/${sid}/events`')
    const eventSource = source.indexOf('new EventSource(eventsURL)', eventsURL)
    const ready = source.indexOf("source.addEventListener('ready', syncQueue)", eventSource)
    const changed = source.indexOf("source.addEventListener('queue_changed', syncQueue)", ready)
    const fallback = source.lastIndexOf('window.setInterval(syncQueue, 3000)', eventsURL)
    const calibration = source.indexOf('window.setInterval(syncQueue, 60000)', eventSource)
    const cleanup = source.indexOf('source?.close()', calibration)
    expect(eventsURL).toBeGreaterThan(-1)
    expect(fallback).toBeGreaterThan(-1)
    expect(fallback).toBeLessThan(eventsURL)
    expect(eventSource).toBeGreaterThan(eventsURL)
    expect(ready).toBeGreaterThan(eventSource)
    expect(changed).toBeGreaterThan(ready)
    expect(calibration).toBeGreaterThan(changed)
    expect(cleanup).toBeGreaterThan(calibration)
  })
})
