import React from 'react'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { api } from '../lib/api'
import ChatVersionBadge from './ChatVersionBadge'
vi.mock('../lib/api', () => ({ api: vi.fn() }))

afterEach(() => cleanup())
beforeEach(() => { api.mockReset() })

it('starts closed, shows the real version, and toggles without fetching update state', async () => {
  api.mockResolvedValue({ version: 'v0.3.21' })
  render(<ChatVersionBadge><button>Settings</button><select aria-label="GA instance"><option>Default</option></select></ChatVersionBadge>)
  const toggle = await screen.findByRole('button', { name: 'GenericAgent Admin v0.3.21' })
  expect(toggle.getAttribute('aria-expanded')).toBe('false')
  expect(screen.queryByRole('dialog')).toBeNull()
  expect(screen.queryByRole('button', { name: 'Settings' })).toBeNull()
  expect(api.mock.calls.map(([path]) => path)).toEqual(['/api/version/info'])
  fireEvent.click(toggle)
  expect(toggle.getAttribute('aria-expanded')).toBe('true')
  expect(screen.getByRole('dialog').parentElement).toBe(document.body)
  expect(screen.getByRole('button', { name: 'Settings' })).toBeTruthy()
  expect(screen.getByRole('combobox', { name: 'GA instance' })).toBeTruthy()
  fireEvent.click(toggle)
  expect(screen.queryByRole('dialog')).toBeNull()
  expect(screen.queryByRole('combobox')).toBeNull()
  expect(screen.queryByRole('dialog')).toBeNull()
  expect(api.mock.calls.map(([path]) => path)).toEqual(['/api/version/info'])
})

it('supports keyboard, instance changes, action close, Escape and outside dismiss', async () => {
  const settings = vi.fn()
  const switchInstance = vi.fn()
  const user = userEvent.setup()
  render(<ChatVersionBadge version="v0.3.21"><select aria-label="GA instance" onChange={event => switchInstance(event.target.value)}><option value="default">Default</option><option value="test">Test</option></select><button onClick={settings}>Settings</button></ChatVersionBadge>)
  const toggle = screen.getByRole('button', { name: 'GenericAgent Admin v0.3.21' })
  await user.tab()
  await user.keyboard('{Enter}')
  const select = screen.getByRole('combobox')
  expect(document.activeElement).toBe(select)
  await user.selectOptions(select, 'test')
  expect(switchInstance).toHaveBeenCalledWith('test')
  expect(screen.getByRole('dialog')).toBeTruthy()
  await user.tab()
  await user.keyboard('{Enter}')
  expect(settings).toHaveBeenCalledTimes(1)
  expect(screen.queryByRole('dialog')).toBeNull()
  toggle.focus()
  await user.keyboard(' ')
  await user.keyboard('{Escape}')
  expect(screen.queryByRole('dialog')).toBeNull()
  expect(document.activeElement).toBe(toggle)
  await user.keyboard(' ')
  fireEvent.pointerDown(document.body)
  expect(screen.queryByRole('dialog')).toBeNull()
  expect(api).not.toHaveBeenCalled()
})

it('does not fetch for supplied preview versions, and shows a safe fallback when loading fails', async () => {
  const preview = render(<ChatVersionBadge version="Preview"/>)
  expect(screen.getByRole('button', { name: 'GenericAgent Admin Preview' })).toBeTruthy()
  expect(api).not.toHaveBeenCalled()
  preview.unmount()
  api.mockRejectedValue(new Error('offline'))
  render(<ChatVersionBadge/>)
  await waitFor(() => expect(screen.getByRole('button', { name: 'GenericAgent Admin ?' })).toBeTruthy())
  fireEvent.click(screen.getByRole('button', { name: 'GenericAgent Admin ?' }))
  expect(screen.getByRole('button').getAttribute('aria-expanded')).toBe('true')
})
