import React from 'react'
import { afterEach, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import SidebarCustomization, { SidebarSections, SidebarTabs, SidebarSectionOptions } from './SidebarCustomization'
import { normalizeSidebarLayout } from '../lib/chatSidebarPreferences.js'
const ct = (_, en) => en
afterEach(cleanup)
const openTabMenu = name => {
  const tab = screen.getByRole('tab', {name})
  if (tab.getAttribute('aria-selected') !== 'true') fireEvent.click(tab)
  fireEvent.click(tab)
}
it('selects inactive tabs first and opens the menu on a second click without a more button', () => {
  const update = vi.fn()
  const layout = normalizeSidebarLayout({tabs:[{id:'work',name:'Work'}]})
  const view = render(<SidebarTabs preferences={{sectionLayout:layout}} update={update} ct={ct}/>)
  const work = screen.getByRole('tab', {name:'Work'})
  expect(document.querySelector('.oa-project-reorder')).toBeNull()
  expect(work.getAttribute('aria-haspopup')).toBe('menu')
  fireEvent.click(work)
  expect(document.querySelector('.oa-sidebar-tab-menu')).toBeNull()
  expect(update).toHaveBeenCalledTimes(1)
  const selected = update.mock.calls[0][1](layout)
  expect(selected.active).toBe('work')
  view.rerender(<SidebarTabs preferences={{sectionLayout:selected}} update={update} ct={ct}/>)
  fireEvent.click(work)
  expect(work.getAttribute('aria-expanded')).toBe('true')
  expect(document.querySelector('.oa-sidebar-tab-menu').parentElement).toBe(document.body)
  expect(document.activeElement.textContent).toBe('Rename')
  expect(update).toHaveBeenCalledTimes(1)
  fireEvent.keyDown(document, {key:'Escape'})
  expect(work.getAttribute('aria-expanded')).toBe('false')
  expect(document.activeElement).toBe(work)
  fireEvent.doubleClick(work)
  expect(screen.queryByRole('dialog')).toBeNull()
  fireEvent.click(work)
  fireEvent.pointerDown(screen.getByRole('tab', {name:'Home'}))
  fireEvent.click(screen.getByRole('tab', {name:'Home'}))
  expect(document.querySelector('.oa-sidebar-tab-menu')).toBeNull()
})
it('uses accessible icon tabs by default and honors explicit visible names', () => {
  const layout = normalizeSidebarLayout({ tabs: [{ id: 'work', name: 'Work' }, { id: 'named', name: 'Named', hideName: false }] })
  render(<SidebarTabs preferences={{sectionLayout:layout}} update={vi.fn()} ct={ct}/> )
  for (const name of ['Home', 'Work']) {
    const tab = screen.getByRole('tab', {name})
    expect(tab.querySelector('svg')).not.toBeNull()
    expect(tab.textContent).toBe('')
    expect(tab.title).toBe(name)
  }
  expect(screen.getByRole('tab', {name:'Named'}).textContent).toBe('Named')
})
it('edits visibility and restores layout without deleting content', () => {
  const update = vi.fn()
  render(<SidebarCustomization preferences={{showProjects:true}} update={update} ct={ct}/> )
  expect(screen.getByRole('button', {name:'Reorder Projects'})).toBeTruthy()
  expect(screen.queryByRole('checkbox')).toBeNull()
  fireEvent.click(screen.getByRole('button', {name:'Projects section settings'}))
  fireEvent.click(screen.getByRole('button', {name:'Hide section'}))
  expect(update).toHaveBeenCalledWith('showProjects', false)
  fireEvent.click(screen.getByRole('button', {name:'Restore default sections'}))
  expect(update).toHaveBeenCalledWith('sectionLayout', normalizeSidebarLayout())
  for (const key of ['showPinned','showConductor','showProjects','showRecent']) expect(update).toHaveBeenCalledWith(key, true)
})
it('reorders sections, filters by active tab and keeps edit content visible', () => {
  const children = [<div key="search">Search</div>, <section key="p" data-sidebar-section="projects">Projects</section>, <section key="r" data-sidebar-section="recent">Recent</section>]
  const layout = normalizeSidebarLayout({tabs:[{id:'work',name:'Work'}],sections:{projects:{tab:'work'}}})
  const view = render(<SidebarSections order={['recent','projects']} layout={layout}>{children}</SidebarSections>)
  expect(view.container.textContent).toBe('SearchRecent')
  view.rerender(<SidebarSections order={['recent','projects']} layout={{...layout,active:'work'}}>{children}</SidebarSections>)
  expect(view.container.textContent).toBe('SearchProjects')
  expect(view.container.firstChild.hidden).toBe(false)
  view.rerender(<SidebarSections hidden order={['recent','projects']} layout={{...layout,active:'work'}}>{children}</SidebarSections>)
  expect(view.container.firstChild.hidden).toBe(true)
  expect(view.container.textContent).toBe('SearchProjects')
})
it('adds hidden sections and moves existing sections without losing their settings', () => {
  const update = vi.fn()
  const layout = normalizeSidebarLayout({tabs:[{id:'work',name:'Work'}],active:'work',sections:{projects:{tab:'work',count:20},recent:{tab:'home',count:50}}})
  render(<SidebarCustomization preferences={{sectionLayout:layout,showProjects:false}} update={update} ct={ct}/>)
  expect(screen.queryByRole('button', {name:'Reorder Projects'})).toBeNull()
  fireEvent.click(screen.getByRole('button', {name:'Add section'}))
  fireEvent.click(screen.getByRole('menuitemradio', {name:'Projects'}))
  expect(update).toHaveBeenCalledWith('showProjects', true)
  expect(update).toHaveBeenCalledWith('sectionLayout', expect.objectContaining({sections:expect.objectContaining({projects:{tab:'work',count:20}})}))
  fireEvent.click(screen.getByRole('button', {name:'Add section'}))
  fireEvent.click(screen.getByRole('menuitemradio', {name:'Recent (move to this tab)'}))
  expect(update).toHaveBeenCalledWith('showRecent', true)
  expect(update.mock.calls.at(-1)[1].sections.recent).toEqual({tab:'work',count:50})
})
it('creates, renames and deletes tabs while moving sections home', () => {
  const update = vi.fn()
  const layout = normalizeSidebarLayout({tabs:[{id:'work',name:'Work'}],active:'work',sections:{projects:{tab:'work',count:20}}})
  render(<SidebarTabs preferences={{sectionLayout:layout}} update={update} ct={ct}/> )
  openTabMenu('Work')
  fireEvent.click(screen.getByRole('button',{name:'Rename'}))
  fireEvent.change(screen.getByLabelText('Tab name'),{target:{value:'Office'}})
  fireEvent.submit(screen.getByLabelText('Tab name').closest('form'))
  expect(update.mock.calls.at(-1)[1].tabs[1].name).toBe('Office')
  openTabMenu('Work')
  fireEvent.click(screen.getByRole('button',{name:'Delete tab'}))
  expect(update.mock.calls.at(-1)[1].sections.projects).toEqual({tab:'home',count:20})
  fireEvent.click(screen.getByRole('button',{name:'New tab'}))
  fireEvent.change(screen.getByLabelText('Tab name'),{target:{value:'Personal'}})
  fireEvent.submit(screen.getByLabelText('Tab name').closest('form'))
  expect(update.mock.calls.at(-1)[1].tabs.at(-1).name).toBe('Personal')
})
it('section menus change count, order and tab ownership', () => {
  const update = vi.fn()
  render(<SidebarSectionOptions section="recent" preferences={{}} update={update} ct={ct}/> )
  fireEvent.mouseEnter(screen.getByRole('button',{name:'Show · 10'}).parentElement)
  fireEvent.click(screen.getByRole('button',{name:'Show · 10'}))
  fireEvent.click(screen.getByRole('menuitemradio',{name:'20 items'}))
  expect(update.mock.calls.at(-1)[1].sections.recent.count).toBe(20)
  fireEvent.click(screen.getByRole('button',{name:'Move up'}))
  expect(update).toHaveBeenCalledWith('sectionOrder',['pinned','conductors','recent','projects'])
  expect(screen.getByRole('button',{name:'Move down'}).disabled).toBe(true)
  fireEvent.click(screen.getByRole('button',{name:'Move to new tab'}))
  const next = update.mock.calls.at(-1)[1]
  expect(next.sections.recent.tab).toBe(next.active)
  expect(next.tabs.at(-1).id).toBe(next.active)
})

it('opens an anchored one-line editor with the default name fully selected', () => {
  const update = vi.fn()
  render(<SidebarTabs preferences={{}} update={update} ct={ct}/>)
  const trigger = screen.getByRole('button', {name:'New tab'})
  fireEvent.click(trigger)
  const input = screen.getByLabelText('Tab name')
  expect(document.activeElement).toBe(input)
  expect(input.value).toBe('New tab')
  expect(input.selectionStart).toBe(0)
  expect(input.selectionEnd).toBe(input.value.length)
  expect(screen.getByRole('dialog').parentElement).toBe(document.body)
  expect(screen.queryByRole('button', {name:'Save'})).toBeNull()
  fireEvent.keyDown(input, {key:'Escape'})
  expect(screen.queryByRole('dialog')).toBeNull()
  expect(document.activeElement).toBe(trigger)
  expect(update).not.toHaveBeenCalled()
})
it('commits outside clicks, rejects empty names and cancels stale positions', () => {
  const update = vi.fn()
  render(<SidebarTabs preferences={{}} update={update} ct={ct}/>)
  const trigger = screen.getByRole('button', {name:'New tab'})
  fireEvent.click(trigger)
  fireEvent.change(screen.getByLabelText('Tab name'), {target:{value:'  Personal  '}})
  fireEvent.pointerDown(document.body)
  expect(update).toHaveBeenCalledTimes(1)
  expect(update.mock.calls[0][1].tabs.at(-1).name).toBe('Personal')
  expect(screen.queryByRole('dialog')).toBeNull()
  update.mockClear()
  fireEvent.click(trigger)
  fireEvent.change(screen.getByLabelText('Tab name'), {target:{value:'   '}})
  fireEvent.submit(screen.getByRole('dialog'))
  expect(screen.getByRole('dialog')).toBeTruthy()
  fireEvent.pointerDown(document.body)
  expect(update).not.toHaveBeenCalled()
  fireEvent.click(trigger)
  fireEvent.resize(window)
  expect(screen.queryByRole('dialog')).toBeNull()
  fireEvent.click(trigger)
  fireEvent.scroll(window)
  expect(screen.queryByRole('dialog')).toBeNull()
  expect(update).not.toHaveBeenCalled()
})
it('renames through the tab menu and prevents Enter during IME composition', () => {
  const update = vi.fn()
  const layout = normalizeSidebarLayout({tabs:[{id:'work',name:'Work',hideName:false}],active:'work'})
  render(<SidebarTabs preferences={{sectionLayout:layout}} update={update} ct={ct}/>)
  openTabMenu('Work')
  fireEvent.click(screen.getByRole('button', {name:'Rename',exact:true}))
  const input = screen.getByLabelText('Tab name')
  expect(input.value).toBe('Work')
  const composing = new KeyboardEvent('keydown', {key:'Enter',isComposing:true,bubbles:true,cancelable:true})
  fireEvent(input, composing)
  expect(composing.defaultPrevented).toBe(true)
  expect(update).not.toHaveBeenCalled()
  fireEvent.change(input, {target:{value:'Office'}})
  fireEvent.submit(screen.getByRole('dialog'))
  expect(update.mock.calls.at(-1)[1].tabs[1]).toEqual({id:'work',name:'Office',hideName:false,icon:'grid'})
})
it('does not create beyond the tab limit even if it changes while naming', () => {
  const update = vi.fn()
  const view = render(<SidebarTabs preferences={{}} update={update} ct={ct}/>)
  fireEvent.click(screen.getByRole('button', {name:'New tab'}))
  const layout = normalizeSidebarLayout({tabs:Array.from({length:11}, (_,i)=>({id:`tab-${i}`,name:`Tab ${i}`}))})
  view.rerender(<SidebarTabs preferences={{sectionLayout:layout}} update={update} ct={ct}/>)
  expect(screen.getByRole('button', {name:'New tab'}).disabled).toBe(true)
  fireEvent.submit(screen.getByRole('dialog'))
  expect(update).not.toHaveBeenCalled()
  expect(screen.queryByRole('dialog')).toBeNull()
})
it('preserves the outside rename when switching to another tab', () => {
  function Harness() {
    const [layout, setLayout] = React.useState(() => normalizeSidebarLayout({tabs:[{id:'work',name:'Work'}]}))
    return <SidebarTabs preferences={{sectionLayout:layout}} update={(_, value)=>setLayout(current=>typeof value === 'function' ? value(current) : value)} ct={ct}/>
  }
  render(<Harness/>)
  openTabMenu('Work')
  fireEvent.click(screen.getByRole('button', {name:'Rename',exact:true}))
  fireEvent.change(screen.getByLabelText('Tab name'), {target:{value:'Office'}})
  const home = screen.getByRole('tab', {name:'Home'})
  fireEvent.pointerDown(home)
  fireEvent.click(home)
  expect(screen.queryByRole('dialog')).toBeNull()
  expect(screen.queryByRole('tab', {name:'Work'})).toBeNull()
  expect(screen.getByRole('tab', {name:'Office'})).toBeTruthy()
  expect(home.getAttribute('aria-selected')).toBe('true')
})
it('chooses an icon for a new tab without saving the draft prematurely', () => {
  const update = vi.fn()
  render(<SidebarTabs preferences={{}} update={update} ct={ct}/>)
  fireEvent.click(screen.getByRole('button', {name:'New tab'}))
  fireEvent.click(screen.getByRole('button', {name:'Choose icon'}))
  const grid = screen.getByRole('group', {name:'Tab icons'})
  expect(grid.querySelectorAll('button')).toHaveLength(24)
  expect(document.activeElement.getAttribute('aria-label')).toBe('Grid')
  fireEvent.keyDown(document.activeElement, {key:'ArrowRight'})
  expect(document.activeElement.getAttribute('aria-label')).toBe('Folder')
  fireEvent.click(screen.getByRole('button', {name:'Star', exact:true}))
  expect(update).not.toHaveBeenCalled()
  expect(screen.getByRole('button', {name:'Choose icon'}).querySelector('.lucide-star')).not.toBeNull()
  fireEvent.change(screen.getByLabelText('Tab name'), {target:{value:'Favorites'}})
  fireEvent.submit(screen.getByLabelText('Tab name').closest('form'))
  expect(update.mock.calls.at(-1)[1].tabs.at(-1)).toMatchObject({name:'Favorites',icon:'star'})
})
it('changes an existing icon and preserves its name, visibility and assigned sections', () => {
  const update = vi.fn()
  const layout = normalizeSidebarLayout({tabs:[{id:'work',name:'Work',hideName:false,icon:'briefcase'}],sections:{projects:{tab:'work',count:20}},active:'work'})
  render(<SidebarTabs preferences={{sectionLayout:layout}} update={update} ct={ct}/>)
  expect(screen.getByRole('tab', {name:'Work'}).querySelector('.lucide-briefcase')).not.toBeNull()
  openTabMenu('Work')
  fireEvent.click(screen.getByRole('button', {name:'Change icon'}))
  expect(screen.getByRole('button', {name:'Briefcase',exact:true}).getAttribute('aria-pressed')).toBe('true')
  fireEvent.keyDown(document.activeElement, {key:'End'})
  expect(document.activeElement.getAttribute('aria-label')).toBe('Calendar')
  fireEvent.keyDown(document.activeElement, {key:'Home'})
  expect(document.activeElement.getAttribute('aria-label')).toBe('Grid')
  fireEvent.click(screen.getByRole('button', {name:'Rocket',exact:true}))
  fireEvent.pointerDown(document.body)
  const next = update.mock.calls.at(-1)[1]
  expect(next.tabs[1]).toEqual({id:'work',name:'Work',hideName:false,icon:'rocket'})
  expect(next.sections).toEqual(layout.sections)
  expect(next.active).toBe('work')
})
it('dismisses the picker first with Escape and cancels unsaved icon edits', () => {
  const update = vi.fn()
  render(<SidebarTabs preferences={{sectionLayout:normalizeSidebarLayout({tabs:[{id:'work',name:'Work',icon:'folder'}],active:'work'})}} update={update} ct={ct}/>)
  openTabMenu('Work')
  fireEvent.click(screen.getByRole('button', {name:'Rename',exact:true}))
  fireEvent.click(screen.getByRole('button', {name:'Choose icon'}))
  fireEvent.keyDown(document.activeElement, {key:'Escape'})
  expect(screen.queryByRole('group', {name:'Tab icons'})).toBeNull()
  expect(screen.getByLabelText('Tab name')).toBe(document.activeElement)
  fireEvent.click(screen.getByRole('button', {name:'Choose icon'}))
  fireEvent.click(screen.getByRole('button', {name:'Heart',exact:true}))
  fireEvent.keyDown(screen.getByLabelText('Tab name'), {key:'Escape'})
  expect(update).not.toHaveBeenCalled()
  expect(screen.getByRole('tab', {name:'Work'}).querySelector('.lucide-folder')).not.toBeNull()
  expect(screen.queryByRole('dialog')).toBeNull()
})
it('groups the tab menu and enters inline sidebar customization', () => {
  const customize = vi.fn()
  render(<SidebarTabs preferences={{sectionLayout:normalizeSidebarLayout({tabs:[{id:'work',name:'Work',hideName:false}],active:'work'})}} update={vi.fn()} ct={ct} onCustomize={customize}/> )
  openTabMenu('Work')
  const menu = screen.getByLabelText('Manage tab Work', {selector:'.oa-sidebar-tab-menu'})
  expect(menu.parentElement).toBe(document.body)
  expect(menu.querySelectorAll('[role="separator"]')).toHaveLength(2)
  for (const name of ['Rename','Change icon','Delete tab','Hide tab name','Customize sidebar']) expect(screen.getByRole('button', {name,exact:true}).querySelector('svg')).not.toBeNull()
  fireEvent.click(screen.getByRole('button', {name:'Customize sidebar'}))
  expect(customize).toHaveBeenCalledTimes(1)
  expect(document.querySelector('.oa-sidebar-tab-menu')).toBeNull()
})
it('renames home without replacing its default icon and persists explicit icon edits', () => {
  const update = vi.fn()
  const layout = normalizeSidebarLayout({sections:{projects:{tab:'home',count:20}}})
  render(<SidebarTabs preferences={{sectionLayout:layout}} update={update} ct={ct}/> )
  const originalIcon = screen.getByRole('tab', {name:'Home'}).querySelector('svg').innerHTML
  openTabMenu('Home')
  expect(screen.queryByRole('button', {name:'Delete tab'})).toBeNull()
  fireEvent.click(screen.getByRole('button', {name:'Rename',exact:true}))
  expect(screen.getByRole('button', {name:'Choose icon'}).querySelector('svg').innerHTML).toBe(originalIcon)
  fireEvent.change(screen.getByLabelText('Tab name'), {target:{value:'Inbox'}})
  fireEvent.submit(screen.getByLabelText('Tab name').closest('form'))
  const renamed = normalizeSidebarLayout(update.mock.calls.at(-1)[1])
  expect(renamed.tabs[0]).toEqual({id:'home',name:'Inbox'})
  expect(renamed.sections).toEqual(layout.sections)
  openTabMenu('Home')
  fireEvent.click(screen.getByRole('button', {name:'Change icon'}))
  fireEvent.click(screen.getByRole('button', {name:'Heart',exact:true}))
  fireEvent.submit(screen.getByLabelText('Tab name').closest('form'))
  expect(normalizeSidebarLayout(update.mock.calls.at(-1)[1]).tabs[0].icon).toBe('heart')
})
it('toggles names for home and custom tabs and preserves ownership through normalization', () => {
  function Harness() {
    const [layout, setLayout] = React.useState(() => normalizeSidebarLayout({tabs:[{id:'work',name:'Work'}],active:'work',sections:{projects:{tab:'work',count:20}}}))
    return <SidebarTabs preferences={{sectionLayout:layout}} update={(_, value)=>setLayout(current=>normalizeSidebarLayout(typeof value === 'function' ? value(current) : value))} ct={ct}/>
  }
  render(<Harness/> )
  for (const name of ['Home','Work']) {
    openTabMenu(name)
    if (name === 'Home') expect(screen.queryByRole('button', {name:'Delete tab'})).toBeNull()
    fireEvent.click(screen.getByRole('button', {name:'Show tab name'}))
    expect(screen.getByRole('tab', {name}).textContent).toBe(name)
    openTabMenu(name)
    fireEvent.click(screen.getByRole('button', {name:'Hide tab name'}))
    expect(screen.getByRole('tab', {name}).textContent).toBe('')
  }
  expect(screen.getByRole('tab', {name:'Work'}).getAttribute('aria-selected')).toBe('true')
  openTabMenu('Work')
  fireEvent.click(screen.getByRole('button', {name:'Delete tab'}))
  expect(screen.queryByRole('tab', {name:'Work'})).toBeNull()
  expect(screen.getByRole('tab', {name:'Home'}).getAttribute('aria-selected')).toBe('true')
})
